=== Qumulo/QumuloAlerts/config/consumer/schema/QumuloEmailServer.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "EmailServer",
    "description": "A schema to validate the EmailServer config file for QumuloEmail",
    "type": "object",
    "properties":
    {
        "from_addr": {"type": "string"},
        "to_addr": {"type": "string"},
        "login": {"type": "string"},
        "password": {"type": "string"},
        "server": {"type": "string", "format": "hostname"},
        "port": {"type": "integer"},
        "use": {"type": "string", "oneOf": [{"enum": ["tls", "ssl", "none"]}]},
        "default_timezone": {"type":  "string", "default": "UTC"},
        "default_language": {"type": "string", "default":  "en"}
    },
    "required":
    [
        "from_addr",
        "to_addr",
        "server",
        "port"
    ]
}

=== Qumulo/QumuloAlerts/config/email/QumuloEmailServer.json
{
    "from_addr": "mike@mikda.com",
    "to_addr": "mkade@qumulo.com",
    "login": "apikey",
    "password": "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",
    "server": "smtp.sendgrid.net",
    "port": 465,
    "use": "ssl",
    "default_timezone": "UTC",
    "default_language": "en_GB"
}
