=== Qumulo/QumuloAlerts/config/email/QumuloEmailUsers.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "QumuloEmailUsers",
    "description": "A schema to validate Email Users for QumuloAlerts",
    "type": "array",
    "items":
    {
        "type": "object",
        "required": [
            "full_name",
            "short_name",
            "email_address",
            "notify"
        ],
        "properties":
        {
            "full_name": {"type": "string"},
            "short_name": {"type": "string"},
            "email_address": {"type": "string"},
            "language": {"type": "string"},
            "timezone": {"type": "string"},
            "notify": {"type": "array", "items": {"$ref": "/config/notify_definition"}}
        }
    },

    "$defs":
    {
        "notify_definition":
        {
            "$id": "/config/notify_definition",
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": "NotifyDefinition",
            "description": "Notify item definition",
            "type": "object",
            "properties":
            {
                "category": {"enum": ["Alarms", "Alerts", "Informational"]},
                "subcategory": {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "enabled": {"type": "boolean"}
            },
            "required": ["category", "subcategory", "enabled"]
        }
    }
}

=== Qumulo/QumuloAlerts/config/email/QumuloEmailUsers.json
[
    {
        "full_name": "Michael Kade",
        "short_name": "Mike",
        "email_address": "mkade@qumulo.com",
        "language": "en_US",
        "timezone": "America/Phoenix",
        "notify":
        [
            {
                "category": "Alarms",
                "subcategory": ["Disk", "Node"],
                "enabled": false
            },
            {
                "category": "Alerts",
                "subcategory": ["Quotas"],
                "enabled": true
            }
        ]
    }
]
