=== Qumulo/QumuloAlerts/config/alerts/schema/QumuloDB.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "DBSchema",
    "description": "A schema to validate the DB configuration file for QumuloAlerts",
    "type": "object",
    "required":
    [
	    "url",
	    "org",
	    "token",
        "buckets"
    ],
    "type": "object",
    "properties":
    {
	    "url": {"type": "string"},
	    "org": {"type": "string"},
	    "token": {"type": "string"},
        "buckets": {"type": "array", "items": {"$ref": "/config/bucket_definition"}}
    },

    "$defs":
    {
        "bucket_definition":
        {
            "$id": "/config/bucket_definition",
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": "BucketDefinition",
            "description": "Bucket item definition",
            "type": "object",
            "properties":
            {
                "name": {"type":  "string"},
                "description": {"type":  "string"},
                "retention": {"type":  "integer"}
            },
            "required": ["name", "description", "retention"]
        }
    }
}

=== Qumulo/QumuloAlerts/config/alerts/QumuloDB.json
{
    "url": "http://influxdb:8086",
    "org": "qumulo",
    "token": "36r2JNh87NlYYChGdPMikuMEMf7zh5dImkcl-mwMfx0eUwvCs34Vj11y5SctXLvmkZmPGl9R0qvnAQSQxMH-Xw==",
    "buckets":
    [
        {
            "name": "QumuloAlertsConfig",
            "description": "Bucket to store QumuloAlerts config (versus json files)",
            "type": "config",
            "retention": 0
        },
        {
            "name": "QumuloAlertsMetrics",
            "description": "Bucket to store OpenMetrics data from a Qumulo cluster",
            "type": "metrics",
            "retention": 7776000
        },
        {
            "name": "QumuloAlertsAlarms",
            "description": "Bucket to store alarms and alerts received from QumuloAlerts",
            "type": "alerts",
            "retention": 31536000
        }
    ]
}

=== Qumulo/QumuloAlerts/config/consumer/QumuloDB.json
{
    "url": "http://influxdb:8086",
    "org": "qumulo",
    "token": "36r2JNh87NlYYChGdPMikuMEMf7zh5dImkcl-mwMfx0eUwvCs34Vj11y5SctXLvmkZmPGl9R0qvnAQSQxMH-Xw==",
    "buckets":
    [
        {
            "name": "Qumulo Alerts Config",
            "description": "Bucket to store QumuloAlerts config (versus json files)",
            "type": "config",
            "retention": 0
        },
        {
            "name": "Qumulo Alerts Metrics",
            "description": "Bucket to store OpenMetrics data from a Qumulo cluster",
            "type": "metrics",
            "retention": 7776000
        },
        {
            "name": "Qumulo Alerts Alarms",
            "description": "Bucket to store alarms and alerts received from QumuloAlerts",
            "type": "alerts",
            "retention": 31536000
        }
    ]
}
