=== Qumulo/QumuloAlerts/config/alerts/QumuloAlerts.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "QumuloAlerts",
    "description": "A schema to validate the configuration file for QumuloAlerts",
    "type": "array",
    "items":
    {
        "type": "object",
        "required":
        [
            "cluster_name",
            "cluster_port",
            "cluster_username",
            "cluster_password",
            "nlb",
            "frequency",
            "monitor"
        ],
        "properties":
        {
            "cluster_name": {"type": "string", "format": "hostname"},
            "cluster_port": {"type": "integer"},
            "cluster_username": {"type": "string"},
            "cluster_password": {"type": "string"},
            "nlb": {"type": "boolean"},
            "frequency":
            {
                "type": "object",
                "properties":
                {
                    "seconds": {"type": "integer"},
                    "minutes": {"type": "integer"}
                },
                "oneOf":
                [
                    {"required": ["seconds"]},
                    {"required": ["minutes"]}
                ]
            },
            "monitor": {"type": "array", "items": {"$ref": "/config/monitor_definition"}}
        }
    },

    "$defs":
    {
        "monitor_definition":
        {
            "$id": "/config/monitor_definition",
            "$schema": "http://json-schema.org/draft-07/schema#",
            "title": "MonitorDefinition",
            "description": "Monitor item definition",
            "type": "object",
            "properties":
            {
                "category": {"enum": ["Alarms", "Alerts", "Informational"]},
                "subcategory":
                {
                    "type": "array",
                    "items": {"type": "string"}
                },
                "enabled": {"type": "boolean"},
                "frequency":
                {
                    "type": "object",
                    "properties":
                    {
                        "seconds": {"type": "integer"},
                        "minutes": {"type": "integer"}
                    },
                    "oneOf":
                    [
                        {"required": ["seconds"]},
                        {"required": ["minutes"]}
                    ]
                }
            },
            "required": ["category", "subcategory", "enabled"]
        }
    }
}

=== Qumulo/QumuloAlerts/config/alerts/QumuloAlerts.json
[
    {
        "cluster_name": "groot.eng.qumulo.com",
        "cluster_port": 8000,
        "cluster_username": "admin",
        "cluster_password": "Admin123",
        "nlb": false,
        "frequency": {
            "minutes": 1
        },
        "monitor": [
            {
                "category": "Alerts",
                "subcategory": ["Quotas"],
                "enabled": true
            }
        ]
    },
    {
        "cluster_name": "a4u1-40g.eng.qumulo.com",
        "cluster_port": 8000,
        "cluster_username": "admin",
        "cluster_password": "Qumulo1!",
        "nlb": false,
        "frequency": {
            "seconds": 60
        },
        "monitor": [
            {
                "category": "Alarms",
                "subcategory": ["*"],
                "enabled": false
            },
            {
                "category": "Alerts",
                "subcategory": ["Quotas"],
                "enabled": true
            },
            {
                "category": "Informational",
                "subcategory": ["Test"],
                "enabled": false
            }
        ]
    }
]
